name: On PR Open/Update

concurrency:
  group: quality-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    branches:
      - main
      - beta

jobs:
  pr-checks:
    name: Code Quality & Reliability Checks
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
      issues: write
    env:
      PHP-VERSION: 8.3
      PHP-EXTENSIONS: mbstring, xdebug
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean Up SonarQube Comments
        if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.draft }}
        uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: sonarcloud[bot]
          issue_number: ${{ github.event.number }}

      - name: Validate Commit Messages
        run: ./tools/scripts/validate-commit-msgs.sh

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.PHP-VERSION }}
          extensions: ${{ env.PHP-EXTENSIONS }}
          key: php8.3-ext-cache

      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: ${{ env.PHP-EXTENSIONS }}
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist


      - name: Install Project Dependencies
        run: composer install --no-progress --no-suggest --no-interaction

      - name: Unit Test
        run: composer coverage

      - name: PR SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}

      - name: Branch SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true
            -Dsonar.branch.name=${{ github.ref_name }}
