name: Release

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - beta
      - main

jobs:
  release:
    name: Release New Version
    runs-on: ubuntu-latest
    env:
      PHP-VERSION: 8.4
      PHP-EXTENSIONS: mbstring, xdebug
    steps:
      - name: Generate Bot GH Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Setup PHP Environment
        uses: ./.github/actions/php-setup
        with:
          PHP-VERSION: ${{ env.PHP-VERSION }}
          PHP-EXTENSIONS: ${{ env.PHP-EXTENSIONS }}

      - name: Branch SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true -Dsonar.branch.name=${{ github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15'

      - name: Install node dependencies
        run: |
          npm i -g \
            semantic-release@23 \
            conventional-changelog-conventionalcommits@^7 \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @iwavesmedia/semantic-release-composer \
            @semantic-release/git \
            @semantic-release/github \
            conventional-changelog-conventionalcommits

      - name: Release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: semantic-release
